build:
	g++ -o csvmtrx csvmtrx.cpp

default: build

clean:
	rm -f ./csvmtrx

fresh:
	make clean
	make

install:
	cp ./csvmtrx /usr/local/bin/csvmtrx

uninstall:
	rm -f /usr/local/bin/csvmtrx

test:
	#todo

memtest:
	#todo
